services:
  macos:
    image: dockurr/macos
    container_name: macos
    privileged: true
    environment:
      VERSION: "11"
      RAM_SIZE: 7G
      CPU_CORES: "4"
      DISK_SIZE: 128G
      DISK_TYPE: blk
      ALLOCATE: N
      ARGUMENTS: ""
    devices:
      - /dev/bus/usb
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./storage:/storage
    restart: always
    stop_grace_period: 2m
