[project]
name = "macboat"
version = "0.1.0"
description = "Native Python GTK4 application to manage macOS VMs using Docker"
authors = [
    {name = "InledGroup", email = "hi@inled.es"}
]
dependencies = [
    "pygobject",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
