desktop_file = i18n.merge_file(
  input: 'es.inled.Macboat.desktop.in',
  output: 'es.inled.Macboat.desktop',
  type: 'desktop',
  po_dir: '../po',
  install: true,
  install_dir: join_paths(get_option('datadir'), 'applications')
)

install_data('es.inled.Macboat.png',
  install_dir: join_paths(get_option('datadir'), 'icons/hicolor/512x512/apps')
)
